services:
  nginx:
    image: nginx:latest
    depends_on:
      - server
      - postgres
    ports:
      - "4444:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      mode: global
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: cvss
      POSTGRES_PASSWORD: cvss
      POSTGRES_DB: cvss
    restart: unless-stopped
    deploy:
      mode: global
    volumes:
      - pq_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    build: .
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
    depends_on:
      - postgres

volumes:
  pq_data: