services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: cvss
      POSTGRES_PASSWORD: cvss
      POSTGRES_DB: cvss
    restart: unless-stopped
    ports:
      - "5433:5432"
    deploy:
      mode: global
    volumes:
      - pq_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    build: .
    ports:
      - "4444:4444"
    depends_on:
      - postgres

volumes:
  pq_data: