package space.itoncek.cvss.server.types;

public enum Event {
	TEAM_UPDATE_EVENT,
	MATCH_UPDATE_EVENT,
	MATCH_ARM,
	MATCH_RESET,
	MATCH_START,
	MATCH_RECYCLE,
	MATCH_END,
	SCORE_CHANGED,
	GRAPHICS_UPDATE_EVENT
}
